

name: CICD Pipeline for Postman

on:

  push:

jobs:

  API-testing:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16,18]


    steps:

      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{matrix.node}}
        uses: actions/setup-node@v4

      - name: Installing Newman
        run: npm install -g newman

      - name: Running testcases using Newman
        run: newman run postman_tests/Books.postman_collection.json -e postman_tests/test.postman_environment.json
